# Generated by Django 6.0.2 on 2026-08-01 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paybill_number', models.CharField(blank=True, help_text='M-Pesa Paybill number for deposits.', max_length=20)),
                ('bank_account_details', models.TextField(blank=True, help_text='e.g. Bank Name: XYZ Bank\nAccount Name: KEPTO Sacco\nAccount Number: 1234567890')),
                ('whatsapp_group_link', models.URLField(blank=True, help_text='Invite link to the members WhatsApp group.')),
                ('financial_literacy_video_url', models.URLField(blank=True, help_text='YouTube link for the financial literacy class.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
