# Generated by Django 6.0.2 on 2026-08-01 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='instagram_link',
            field=models.URLField(blank=True, help_text="Link to KEPTO's Instagram profile."),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='whatsapp_group_link',
            field=models.URLField(blank=True, help_text='Invite link to the members WhatsApp group. Also shown as the public contact WhatsApp link.'),
        ),
    ]
