# Generated by Django 6.0.2 on 2026-08-01 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_sitesettings_instagram_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='contact_email',
            field=models.EmailField(blank=True, help_text='Public contact email shown on the site.', max_length=254),
        ),
    ]
