# Generated by Django 6.0.2 on 2026-08-01 14:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_seed_institutions_industries'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='member_id',
            field=models.CharField(blank=True, editable=False, max_length=8, unique=True),
        ),
        migrations.AddField(
            model_name='member',
            name='phone_number',
            field=models.CharField(default='', max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid 10-digit phone number starting with 0 (e.g. 0712345678).', regex='^0\\d{9}$')]),
            preserve_default=False,
        ),
    ]
