# Generated by Django 6.0.2 on 2026-08-19 07:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_member_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="avatar_image",
            field=models.ImageField(blank=True, null=True, upload_to="avatars/"),
        ),
        migrations.AddField(
            model_name="member",
            name="avatar_preset",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="member",
            name="display_name",
            field=models.CharField(
                blank=True,
                help_text="What you want to be called on your dashboard.",
                max_length=30,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Use 1–30 characters: letters, numbers, spaces and . _ , - only.",
                        regex="^[A-Za-z0-9 ._,\\-]{1,30}$",
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="savings_goal",
            field=models.DecimalField(
                decimal_places=2,
                default=10000,
                help_text="Your personal savings target, in KES.",
                max_digits=10,
            ),
        ),
    ]
